#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Change your keymap:
#xmodmap "/root/.Xmodmap"

# Set the background image
wpsetters=feh fbsetbg ~/.fluxbox/backgrounds/gentoo.jpg

#Set X variables
DISPLAY=:0.0 
XAUTHORITY="$( ps -C X f | sed -n 's/.*-auth \(.*\)/\1/p' )"

export DISPLAY
export XAUTHORITY

xhost +local:root

#Set font style
xset +fp /usr/share/fonts/corefonts
xset +fp /usr/share/fonts/100dpi
xset +fp /usr/share/fonts/75dpi
#xset +fp /usr/share/fonts/terminus


# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
# unclutter -idle 2 &
# wmnd &
# wmsmixer -w &
# idesk &

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.

exec fluxbox
# or if you want to keep a log:
# exec fluxbox -log "/root/.fluxbox/log"
